apiVersion: v1
kind: Service
metadata:
  name: moderation-srv-nodeport
spec:
  type: NodePort
  selector: 
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 5003
      targetPort: 5003